name: SonarCloud Analysis

on:
  pull_request:
  push:

jobs:
  sonar:
    runs-on: macos-latest # Cambiado de ubuntu a macos

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build for SonarCloud
        # Generamos el log de compilación que Sonar necesita para Swift
        run: |
          xcodebuild clean build \
            -project SpaceXInsights.xcodeproj \
            -scheme SpaceXInsights \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./DerivedData | tee xcodebuild.log

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=luisvicente2021_SpaceXInsights
            -Dsonar.organization=luisvicente2021
            -Dsonar.sources=.
            -Dsonar.swift.compiler_logpath=xcodebuild.log
            -Dsonar.exclusions=**/DerivedData/**,**/*.plist,**/Assets.xcassets/**
            -Dsonar.verbose=true