name: SonarCloud Analysis

on:
  pull_request:
  push:

jobs:
  sonar:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Instalar el Sonar Scanner manualmente en macOS
      - name: Install SonarScanner
        run: brew install sonar-scanner

      # 2. Compilar el proyecto para generar el log
      - name: Build for SonarCloud
        run: |
          xcodebuild clean build \
            -project SpaceXInsights.xcodeproj \
            -scheme SpaceXInsights \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./DerivedData | tee xcodebuild.log

      # 3. Ejecutar el Scanner usando el binario de brew (No la acción de Docker)
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=luisvicente2021_SpaceXInsights \
            -Dsonar.organization=luisvicente2021 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.swift.compiler_logpath=xcodebuild.log \
            -Dsonar.exclusions=**/DerivedData/**,**/*.plist,**/Assets.xcassets/** \
            -Dsonar.verbose=true